"""Pydantic schemas for CITYSHIELD GIS backend."""
from .optimization import (
    ResourceQuantity,
    ResourceItemAllocation,
    ZoneDemand,
    OptimizationGoal,
    OptimizationConstraint,
    ResourceOptimizationRequest,
    ZoneAllocationResult,
    OptimizationSummary,
    ResourceOptimizationResponse,
    OptimizationStatusResponse,
)

from .flood import (
    SpectralIndexType,
    RasterBoundingBox,
    RasterMetadata,
    SatelliteSceneContract,
    WaterDetectionConfig,
    SurfaceWaterMaskResult,
    PermanentWaterMaskConfig,
    PotentialFloodWaterResult,
    PermanentWaterMaskResult,
    FloodExtentMetrics,
    GeoJSONGeometry,
    GeoJSONFeature,
    GeoJSONFeatureCollection,
    FloodExtentExtractionConfig,
    FloodExtentResponse,
    FloodExtentResult,
)

from .what_if import (
    ZoneModifier,
    ScenarioChanges,
    WhatIfSimulateRequest,
    ResourceDelta,
    ZoneAllocationComparison,
    SimulationSummary,
    WhatIfSimulateResponse,
)
from .timeline import (
    HourlyGrowthRule,
    TimeStepProjection,
    FutureGapTimelineRequest,
    ZoneGapPoint,
    TimelinePoint,
    TimelineSummary,
    FutureGapTimelineResponse,
)
from .response_gap_timeline import (
    DuplicateTimestampPolicy,
    ResponseGapTimeline,
    ResponseGapTimelinePoint,
)
from .gis import (
    ImpactLevel,
    BuildingFootprint,
    WardZoneGeometry,
    BuildingImpactDetail,
    ZoneImpactResult,
    GISImpactSummary,
    FloodImpactRequest,
    FloodImpactResponse,
)
from .flood_response import (
    ZoneBaselineProfile,
    FloodResponseAnalyzeRequest,
    IntegratedZoneResponse,
    FloodResponseAnalyzeResponse,
)
from .city_gis import (
    GeometryType,
    DatasetSource,
    CityMetadata,
    RoadSegment,
    HospitalFacility,
    ShelterFacility,
    PopulationDemographic,
    CityGISInventorySummary,
)
from .copilot import (
    CopilotRole,
    CopilotMessage,
    CopilotToolCall,
    CopilotToolResult,
    CopilotRequest,
    CopilotResponse,
    CityGISLayerType,
    GetCityGISDataArgs,
    AssessFloodGISImpactArgs,
    OptimizeResourceAllocationArgs,
    SimulateWhatIfScenarioArgs,
    ProjectFutureGapTimelineArgs,
    RunEndToEndFloodResponseArgs,
)

__all__ = [
    "ResourceQuantity",
    "ResourceItemAllocation",
    "ZoneDemand",
    "OptimizationGoal",
    "OptimizationConstraint",
    "ResourceOptimizationRequest",
    "ZoneAllocationResult",
    "OptimizationSummary",
    "ResourceOptimizationResponse",
    "OptimizationStatusResponse",

    "SpectralIndexType",
    "RasterBoundingBox",
    "RasterMetadata",
    "SatelliteSceneContract",
    "WaterDetectionConfig",
    "SurfaceWaterMaskResult",
    "PermanentWaterMaskConfig",
    "PotentialFloodWaterResult",
    "PermanentWaterMaskResult",
    "FloodExtentMetrics",
    "GeoJSONGeometry",
    "GeoJSONFeature",
    "GeoJSONFeatureCollection",
    "FloodExtentExtractionConfig",
    "FloodExtentResponse",
    "FloodExtentResult",

    "ZoneModifier",
    "ScenarioChanges",
    "WhatIfSimulateRequest",
    "ResourceDelta",
    "ZoneAllocationComparison",
    "SimulationSummary",
    "WhatIfSimulateResponse",

    "HourlyGrowthRule",
    "TimeStepProjection",
    "FutureGapTimelineRequest",
    "ZoneGapPoint",
    "TimelinePoint",
    "TimelineSummary",
    "FutureGapTimelineResponse",
    "ResponseGapTimelinePoint",
    "ResponseGapTimeline",
    "DuplicateTimestampPolicy",

    "ImpactLevel",
    "BuildingFootprint",
    "WardZoneGeometry",
    "BuildingImpactDetail",
    "ZoneImpactResult",
    "GISImpactSummary",
    "FloodImpactRequest",
    "FloodImpactResponse",

    "ZoneBaselineProfile",
    "FloodResponseAnalyzeRequest",
    "IntegratedZoneResponse",
    "FloodResponseAnalyzeResponse",

    "GeometryType",
    "DatasetSource",
    "CityMetadata",
    "RoadSegment",
    "HospitalFacility",
    "ShelterFacility",
    "PopulationDemographic",
    "CityGISInventorySummary",

    "CopilotRole",
    "CopilotMessage",
    "CopilotToolCall",
    "CopilotToolResult",
    "CopilotRequest",
    "CopilotResponse",
    "CityGISLayerType",
    "GetCityGISDataArgs",
    "AssessFloodGISImpactArgs",
    "OptimizeResourceAllocationArgs",
    "SimulateWhatIfScenarioArgs",
    "ProjectFutureGapTimelineArgs",
    "RunEndToEndFloodResponseArgs",
]
